/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.requestsystemwritepermission;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import android.Manifest;
import android.app.Activity;
import android.content.pm.PackageManager;
import android.os.Build;


@Kroll.module(name="Tirequestsystemwritepermission", id="de.appwerft.requestsystemwritepermission")
public class TirequestsystemwritepermissionModule extends KrollModule {

	// Standard Debugging variables
	private static final String LCAT = "TirequestsystemwritepermissionModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public TirequestsystemwritepermissionModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

    // Methods
    @Kroll.method
    private boolean hasStoragePermission() {
        if (Build.VERSION.SDK_INT < 23) {
            return true;
        }
        Activity currentActivity = TiApplication.getInstance().getCurrentActivity();
        if (currentActivity.checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE) == PackageManager.PERMISSION_GRANTED) {
            return true;
        }
        return false;
    }
    
    @Kroll.method
    public void requestSystemWritePermissions(@Kroll.argument(optional=true)KrollFunction permissionCallback)
    {
        if (hasStoragePermission()) {
            return;
        }
        // TODO
        if (TiBaseActivity.cameraCallbackContext == null) {
            TiBaseActivity.cameraCallbackContext = getKrollObject();
        }
        TiBaseActivity.cameraPermissionCallback = permissionCallback;
        String[] permissions = null;
        permissions = new String[] {Manifest.permission.WRITE_SYSTEM};
        
        
        Activity currentActivity = TiApplication.getInstance().getCurrentActivity();
        // TODO
        currentActivity.requestPermissions(permissions, TiC.PERMISSION_CODE_CAMERA);
        
    }

}

